### ISSUE TITLE
Fix the gh-pages index.html

### ISSUE THREAD

**Issue by bhalothia** [TheRemoteLab/awesome-learning#10]
@ramitsurana I have updated the readme.md file and changed the structure of the repository. I haven't had the time to look at how the index.html gets generated. Is it dynamic? Can you please align it with the changes?

**Comment by ramitsurana** [comment]
I have uploaded the new website on the gh-pages branch.Please check it out.

**Comment by bhalothia** [comment]
Love it. :heart_eyes:
